### ISSUE TITLE
Is it possible to provide sync function?

### ISSUE THREAD

**Issue by w2043t** [retifrav/rclone-rc-web-gui#10]
The web is quite useful. But is it possible to provide "sync" function? Copy and Move functions are not enough for me.

**Comment by retifrav** [comment]
Oops, somehow I never noticed this request. But anyway, I didn't plan to have `sync` from the very beginning, as I only needed `copy` and `move` (*and `delete`*).

I imagine, it would be rather trivial to add `sync`, but I don't need it and actually I don't want it, as this command is potentially dangerous (*a weapon of mass destruction, comparing to `move`/`delete`*), and I'd like to keep my UI "safe".
Anyone else is free to add it though, but preferably in their own fork.
