### ISSUE TITLE
Hiding Password

### ISSUE THREAD

**Issue by szbk** [retifrav/rclone-rc-web-gui#11]
Is there a way to hide the username and passwords we have saved in setting.js?

**Comment by retifrav** [comment]
Sorry, I only now noticed this question. Strangely, I had notifications disabled for this repository.

Regarding your question, it is assumed that user trusts the host that serves the web GUI and/or that this host has restricted access. So I kept things simple, and credentials are stored in plain text there.

If someone has an idea of how this could be handled differently, do share your suggestions.

I actually can't immediately think of a way of protecting these credentials, should that be required. Perhaps an external secrets storage could be used, but I haven't explored this possibility.
