### ISSUE TITLE
rclone unknown

### ISSUE THREAD

**Issue by dduuyt** [retifrav/rclone-rc-web-gui#19]
I am currently trying to host this web gui on a remote vps , but it keeps showing this unknown error and i can not access any of my rclone configs .this is the command i tried
```
 rclone rcd --transfers 1 --rc-allow-origin http://public-ip:5572 \
    --rc-web-gui --rc-web-gui-no-open-browser --rc-addr :5572 \
    --rc-web-fetch-url https://api.github.com/repos/retifrav/rclone-rc-web-gui/releases/latest
``` 
![image](https://github.com/retifrav/rclone-rc-web-gui/assets/111257520/1812ffb9-e0bc-4d80-9449-6f6c93c4bbdd)

**Comment by retifrav** [comment]
What does it output in browser console? Hopefully, there are some error details there.

**Comment by dduuyt** [comment]
![image](https://github.com/retifrav/rclone-rc-web-gui/assets/111257520/72f97ec1-9942-4a73-b7b2-20b13db3b838)
this is what i get from the console

**Comment by dduuyt** [comment]
accidentally bumped into the rights settings , leave this for future noobs who may met this problem
# settings.js
```
export const guiVersion = "0.4.0";
export const rcloneSettings = {
    host: "http://server-ip:5572",
    // null if --rc-no-auth, otherwise what is set in --rc-user
    user: "username",
    // null if --rc-no-auth, otherwise what is set in --rc-pass
    pass: "password",
    // null if there is no login_token in URL query parameters,
    // otherwise is set from there and takes over user/pass
    loginToken: null
};
``` 

# cmd line
```
rclone rcd --transfers 1 --rc-allow-origin http://server-ip:5572 \
    --rc-web-gui --rc-user=username --rc-pass=password --rc-web-gui-no-open-browser --rc-addr :5572 \
    --rc-web-fetch-url https://api.github.com/repos/retifrav/rclone-rc-web-gui/releases/latest
```

**Comment by retifrav** [comment]
That was already described in the README.
